# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)
#♥️

Business.create!(name: "Black Flag Apparel", city: "Staten Island", state: "NY", summary: "Black Flag: Never Give Up 🏴", categories: "Coaching,Fashion,Non Profit", website: "BFNGU.com", twitter:"https://twitter.com/N_everG_iveU_p",img_url:"https://cdn.dribbble.com/users/908023/screenshots/7195388/media/da178ba79a307d5fb608e6307507c2cc.png",hearts:0)
Business.create!(name: "Jaded Faces", city: "Staten Island", state: "NY", summary: "Skin care , Lash and beauty asthetic work. Yee", categories: "Fashion,Beauty & Hair", website: "JF.com", twitter:"https://twitter.com/N_everG_iveU_p",img_url:"https://blackgirlish.files.wordpress.com/2015/05/d80076c65d952bb3e4bc6aca4d6a9404.jpg",hearts:0)
Business.create!(name: "Panama Pleasures", city: "Bronx", state: "NY", summary: "Real Bitch Shit🇵🇦", categories: "Music,Recreation", website: "PANAMADIMES.com", twitter:"https://twitter.com/N_everG_iveU_p",img_url:"https://media1.giphy.com/media/xUOxfmphm9wCmqQ94A/giphy.gif",hearts:0)
Business.create!(name: "DreamChasers", city: "Miami", state: "FL", summary: "Manifest your dreams we chasing dreams out here all i just thought of that dreamchasers yall like that?", categories: "Film & Photography,Coaching,Education", website: "PANAMADIMES.com", twitter:"https://twitter.com/N_everG_iveU_p",img_url:"https://tinyurl.com/y3nrpp36",hearts:0)
Business.create!(name: "MVPizzas", city: "Orlando", state: "FL", summary: "Just a quick project we working on during our stay in Orlando I promise I'll make it to every event 😁", categories: "Food", website: "MVP.com", twitter:"https://twitter.com/N_everG_iveU_p",img_url:"https://www.qsrmagazine.com/sites/default/files/styles/story_page/public/story/all-hail-king.jpg?itok=eC4lUUai",hearts:0)
Business.create!(name: "BARS Lessons", city: "Compton", state: "CA", summary: "I'm available for tutoring for your favorite mumble rapper", categories: "Music,Coaching,Education", website: "KDOT.com", twitter:"https://twitter.com/N_everG_iveU_p",img_url:"https://tinyurl.com/yyswq49c",hearts:0)

User.create!(name: "Anthony Holder", username: "TripleP", website: "LOA.com", img_url:"https://image.freepik.com/free-photo/burning-wood-night_149066-1410.jpg", email:"adot@a.com")
User.create!(name: "Jada Gordon", username: "JadaG", website: "JF.com", img_url:"https://thelearnedfangirl.com/wp-content/uploads/2014/06/Michiko-to-Hatchin-michiko-to-hatchin-32569498-1280-720.jpg", email:"yerrr@gmail.com")
User.create!(name: "Diamond Clark", username: "Panama", website: "PP.com", img_url:"https://images.fineartamerica.com/images-medium-large-5/panama-flag-vintage-distressed-finish-design-turnpike.jpg", email:"ayeee@gmail.com")
User.create!(name: "B Simone", username: "manifestqueen", website: "bsimone@wilinout.com", img_url:"https://images.complex.com/complex/images/c_fill,f_auto,g_center,w_1200/fl_lossy,pg_1/iluszp7ojjqfx22gy0qn/b-simone", email:"bsimone@wilinout.com")
User.create!(name: "Lebron James", username: "King_James", website: "Witness.com", img_url:"https://hollywoodunlocked.com/wp-content/uploads/2020/02/LBJ-GIF.gif",email:"lbj@goat.com")
User.create!(name: "Kendrick Lamar", username: "Kdot", website: "TopDawgEnt.com", img_url:"https://static.billboard.com/files/media/kendrick-lamar-smile-2017-a-billboard-a-1548-1024x677.jpg",email:"maddkid@goodcitydamn.com")
User.create!(name: "Stephen A. Smith", username: "SAS", website: "SAS.com", img_url:"https://pbs.twimg.com/profile_images/1246151237889921032/i4QYCOHi_400x400.jpg",email:"SAS@sportscenter.com")
User.create!(name: "Jay Z", username: "Hov", website: "Roc.com", img_url:"https://24.media.tumblr.com/08894f43398612a406be7d16bcc64b01/tumblr_mi5847sdiF1r877b7o1_250.gif",email:"throwupalungwhereyoufrommarcyson@bk.com")
User.create!(name: "Beyoncé", username: "Queen_B", website: "QB.com", img_url:"https://i.pinimg.com/originals/56/43/3b/56433b4638d2b6fc1e06c81244370a7e.gif", email:"queenBey@gmail.com")
User.create!(name: "Barack Obama", username: "BarryO", website: "44.com", img_url:"https://tinyurl.com/yxkps93r", email:"goatpres@usa.com")

UserBiz.create!(user_id:1, business_id:1)
UserBiz.create!(user_id:2, business_id:2)
UserBiz.create!(user_id:3, business_id:3)
UserBiz.create!(user_id:4, business_id:4)
UserBiz.create!(user_id:5, business_id:5)
UserBiz.create!(user_id:6, business_id:6)

Comment.create!(user_id:1, business_id:1, content:"test1", score:12)
Comment.create!(user_id:2, business_id:2, content:"test2", score:15)
Comment.create!(user_id:3, business_id:3, content:"test3", score:22)
Comment.create!(user_id:3, business_id:1, content:"yee", score:109)
Comment.create!(user_id:2, business_id:2, content:"woot", score:109)
Comment.create!(user_id:4, business_id:2, content:"🔥", score:109)
Comment.create!(user_id:5, business_id:1, content:"issaa comment 💯", score:109)
Comment.create!(user_id:6, business_id:2, content:"issaa comment 💯", score:109)
Comment.create!(user_id:7, business_id:4, content:"just dropped a 50 on you", score:109)
Comment.create!(user_id:8, business_id:5, content:"issaa comment 💯", score:109)
Comment.create!(user_id:9, business_id:6, content:"top 20 😍", score:109)
Comment.create!(user_id:10, business_id:6, content:"issaa comment 💯", score:109)
Comment.create!(user_id:10, business_id:5, content:"issaa comment 💯💯💯", score:109)
Comment.create!(user_id:2, business_id:4, content:"yup", score:10)
Comment.create!(user_id:5, business_id:3, content:"whoa", score:19)
Comment.create!(user_id:7, business_id:2, content:"damn", score:123)
Comment.create!(user_id:5, business_id:1, content:"yu wilin", score:4)
Comment.create!(user_id:6, business_id:2, content:"this heat", score:15)
Comment.create!(user_id:2, business_id:2, content:"issa comment😭", score:1090)
Comment.create!(user_id:10, business_id:3, content:"issaa comment🏴", score:1090)
Comment.create!(user_id:9, business_id:4, content:"issaa comment🎯", score:10222)
Comment.create!(user_id:8, business_id:5, content:"issaa comment", score:17043)
Comment.create!(user_id:8, business_id:6, content:"this a tester", score:123)
Comment.create!(user_id:8, business_id:5, content:"whoaaaa this here wow how they even you really bout to keep reading i aint saying nothing now im just rambling this just an example long ass comment", score:70)
Comment.create!(user_id:3, business_id:4, content:"thats crazy", score:159)
Comment.create!(user_id:4, business_id:5, content:"LeBron bout to be like 😍🏆🏆🏆🏆", score:5109)
Comment.create!(user_id:1, business_id:3, content:"this is the defining year of our lifeti-- shut up and turn up that WAP!", score:33109)
Comment.create!(user_id:2, business_id:6, content:"none ya talking bout the business", score:1039)